[pyprland]
plugins = [
  "scratchpads"
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
position = "17% 5%"
size = "70% 60%"
offset = "200%"

[scratchpads.btop]
animation = "fromLeft"
command = "kitty --class kitty-taskbar -e btop"
class = "kitty-taskbar"
size = "60% 80%"
offset = "200%"

[scratchpads.clipse]
animation = "fromRight"
command = "kitty --class kitty-clipse -e clipse"
class = "kitty-clipse"
size = "45% 80%"
offset = "200%"

[scratchpads.task]
animation = "fromBottom"
command = "kitty --class kitty-task -e taskwarrior-tui"
class = "kitty-task"
size = "60% 60%"
offset = "200%"
