export ZSH="/data/data/com.termux/files/home/.oh-my-zsh"

ZSH_THEME="robbyrussell"

COMPLETION_WAITING_DOTS="true"
set -o vi

plugins=(
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'

source ~/.utility/aliases.sh
source ~/.utility/functions.sh

# Aliases
alias cdd='cd /storage/emulated/0/'

