alias ls="ls --hyperlink=auto --color=auto"
alias py="python3"
alias python="python3"
alias ipy="ipython"
alias duh="du -ha --max-depth=1"
alias gitsc="git clone --depth=1"
alias chx="chmod u+x"
alias c="clear"
alias v="nvim"
alias cls="clear && ls"
alias find="fd"
