#!/usr/bin/env python3
from sys import argv, stdin

if len(argv) != 2:
    for i in stdin.read().split():
        if (i := i.strip()).isnumeric():
            print(f"{i}: {chr(int(i))!r}")
else:
    print(f"{chr(int(argv[1].strip()))!r}")
