#!/usr/bin/env python3
from sys import argv, stdin


def char_rep(n):
    return repr(chr(int(n.strip()))).strip("'")


if len(argv) != 2:
    for i in stdin.read().split():
        if (i := i.strip()).isnumeric():
            print(f"{i}: {char_rep(i)}")
else:
    print(f"{char_rep(argv[1])}")
