#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Connect Warp
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🌩️

# Documentation:
# @raycast.description Connect Cloudflare Warp using its cli
# @raycast.author Arbaaz Shafiq
# @raycast.authorURL https://github.com/s1as3r

warp-cli connect
