#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Disconnect Warp
# @raycast.mode compact

# Optional parameters:
# @raycast.icon ☁️

# Documentation:
# @raycast.description Disonnect Cloudflare Warp using its cli
# @raycast.author Arbaaz Shafiq
# @raycast.authorURL https://github.com/s1as3r

warp-cli disconnect
