#!/usr/bin/env bash
if [[ $# -ne 1 ]]; then
        echo "Usage: gitignore <language>"
        exit 1
fi

wget --quiet --output-document - "https://raw.githubusercontent.com/github/gitignore/refs/heads/main/$1.gitignore"
