#!/usr/bin/env bash
if [[ $# -lt 1 ]]; then
    echo "Usage: gitignore <language>"
    exit 1
fi

if ! command -v "gh" 2>&1 >/dev/null; then
    wget --quiet "https://raw.githubusercontent.com/github/gitignore/refs/heads/main/$1.gitignore" --output-document -
else
    gh repo gitignore view "$1"
fi
