#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title One Liner
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🤖
# @raycast.argument1 { "type": "text", "placeholder": "cool ass one liner" }

# Documentation:
# @raycast.author Arbaaz Shafiq
# @raycast.authorURL https://github.com/s1as3r

echo $(eval "$1")
