#!/usr/bin/env python3
from sys import argv, stdin


def print_ords(inp: str):
    for i in inp:
        print(f"{i!r}: {ord(i)}")


if len(argv) != 2:
    print_ords(stdin.read())
else:
    if len(argv[1]) == 1:
        print(ord(argv[1]))
    else:
        print_ords(argv[1])
