#!/usr/bin/env python3
from sys import argv, stdin


def print_ords(inp: str):
    for i in inp:
        print(f"{i!r}: {ord(i)}")


match argv[1:]:
    case [char] if len(char) == 1:
        print(ord(char))
    case [*words] if words:
        print_ords("".join(words))
    case _:
        print_ords(stdin.read())
