#!/usr/bin/env python3
from argparse import ArgumentParser
from json import loads
from os import getenv
from subprocess import run
from sys import exit, stdout
from typing import NamedTuple, Self


class PhysicalSize(NamedTuple):
    width: int
    height: int


class DisplayMode(NamedTuple):
    width: int
    height: int
    refresh: float
    preferred: bool
    current: bool


class Position(NamedTuple):
    x: int
    y: int


class DisplayInfo(NamedTuple):
    name: str
    description: str
    make: str
    model: str
    serial: str
    physical_size: PhysicalSize
    enabled: bool
    modes: list[DisplayMode]
    position: Position | None = None
    transform: str | None = None
    scale: float | None = None
    adaptive_sync: bool | None = None

    @classmethod
    def from_dict(cls, di: dict) -> Self:
        modes = [DisplayMode(**mode) for mode in di.pop("modes")]
        physical_size = PhysicalSize(**di.pop("physical_size"))
        position_d = di.pop("position", None)
        position = None if position_d is None else Position(**position_d)
        return cls(**di, physical_size=physical_size, position=position, modes=modes)


def get_cli_parser() -> ArgumentParser:
    parser = ArgumentParser(prog="rr", description="change/print refresh rate")
    parser.add_argument(
        "refresh",
        nargs="?",
        type=float,
        metavar="REFRESH_RATE",
    )
    parser.add_argument(
        "--display",
        "-d",
        type=int,
        metavar="N",
        default=getenv("RR_DEFAULT_DISPLAY_NO", 0),
        help="change/print display %(metavar)s's rr"
        + " (default = %(default)s (env: RR_DEFAULT_DISPLAY_NO))",
    )
    return parser


def get_displays() -> list[DisplayInfo]:
    res = run(["wlr-randr", "--json"], capture_output=True)
    res.check_returncode()

    return [DisplayInfo.from_dict(di) for di in loads(res.stdout)]


def show_displays(
    displays: list[DisplayInfo],
) -> None:
    print("Available Displays:")
    for i, display in enumerate(displays):
        print(f"\t[{i}]: {display.name} - {display.description} | {display.enabled}")


def match_rr(available_rr: list[float], query_rr: float) -> None | float:
    for rr in available_rr:
        if abs(rr - query_rr) < 1:
            return rr
    return None


def main():
    args = get_cli_parser().parse_args()
    displays = get_displays()
    if args.display not in range(0, len(displays)):
        print(f"Error: invalid display no ({args.display})")
        show_displays(displays)
        exit(1)

    display = displays[args.display]
    if not display.enabled:
        print(f"Error: display {args.display} not enabled")
        show_displays(displays)
        exit(1)

    current_mode_l = [mode for mode in display.modes if mode.current]
    if not current_mode_l:
        print(f"Error: no current mode found for display {args.display}")
        exit(1)
    current_mode = current_mode_l[0]

    available_rr = sorted(
        {
            mode.refresh
            for mode in display.modes
            if mode.width == current_mode.width and mode.height == current_mode.height
        }
    )
    disp_available_rr = "Available Refresh Rates:\n\t" + "\n\t".join(
        f"{rr}Hz" for rr in available_rr
    )

    if args.refresh is None:
        print(f"Display: {display.name}")
        print(
            f"Current Mode: {current_mode.width}x{current_mode.height}@{current_mode.refresh}"
        )
        print(disp_available_rr)
        exit(0)

    matched_rr = match_rr(available_rr, args.refresh)
    if matched_rr is None:
        print(f"Error: refresh rate ({args.refresh}) not valid for current res")
        print(disp_available_rr)
        exit(1)

    matched_mode = f"{current_mode.width}x{current_mode.height}@{matched_rr}"
    print(f"Changing {display.name} to {matched_mode}")

    exit(
        run(
            ["wlr-randr", "--output", display.name, "--mode", matched_mode],
            stdout=stdout,
        ).returncode
    )


if __name__ == "__main__":
    main()
