#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Word Count
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🔡
# @raycast.argument1 { "type": "text", "placeholder": "Placeholder" }

# Documentation:
# @raycast.description Counts the Word
# @raycast.author Arbaaz Shafiq
# @raycast.authorURL https://github.com/s1as3r

echo "$1" | wc -w

